/**
 * modelRuns.ts
 *
 * Shared provider metadata + a tiny localStorage-backed store that remembers
 * the most recent result set generated by each AI model/provider. This
 * powers:
 *   - the "Model" dropdown on the Search page's generate bar
 *   - the "Generated by" indicator on the results view
 *   - the dashboard's model comparison panel
 */

import type { LLMProvider } from "@/src/lib/careerAgent";
import type { CareerMatch } from "@/src/lib/mockData";
import type { FullAssessmentPayload } from "@/src/lib/types";

// ── Provider metadata ───────────────────────────────────────────────────────

export interface ProviderInfo {
  id: LLMProvider;
  /** Full name shown in the model picker dropdown */
  label: string;
  /** Short name shown in the pill / badges */
  short: string;
}

export const PROVIDER_INFO: ProviderInfo[] = [
  { id: "claude", label: "Claude (Anthropic)", short: "Claude" },
  { id: "openai", label: "OpenAI (GPT-4o mini)", short: "GPT-4o mini" },
  { id: "gemini", label: "Gemini (Google AI Studio)", short: "Gemini" },
  { id: "groq", label: "Groq Cloud", short: "Groq" },
  { id: "openrouter", label: "OpenRouter", short: "OpenRouter" },
];

/**
 * Providers that are wired up in this environment's `.env.local` and safe to
 * offer in the Search page's model picker. Claude and OpenAI are still fully
 * supported by the backend agent (see careerAgent.ts) but are commented out
 * in `.env.local` by default — selecting them without a key set causes the
 * /api/careers route to 500. Once ANTHROPIC_API_KEY / OPENAI_API_KEY are
 * uncommented and filled in, add "claude" / "openai" here to surface them.
 */
export const ENABLED_PROVIDERS: LLMProvider[] = ["gemini", "groq", "openrouter"];

/** PROVIDER_INFO filtered down to just the providers safe to show in the UI. */
export const UI_PROVIDER_INFO: ProviderInfo[] = PROVIDER_INFO.filter((p) =>
  ENABLED_PROVIDERS.includes(p.id)
);

export function providerShortLabel(provider: LLMProvider): string {
  return PROVIDER_INFO.find((p) => p.id === provider)?.short ?? provider;
}

export function providerFullLabel(provider: LLMProvider): string {
  return PROVIDER_INFO.find((p) => p.id === provider)?.label ?? provider;
}

// ── Stored run shape ─────────────────────────────────────────────────────────

export interface ModelRun {
  provider: LLMProvider;
  timestamp: number;
  confidencePercent: number;
  activeVariables: string;
  careers: CareerMatch[];
  /** Wall-clock time (ms) the provider took to generate this result, measured server-side. */
  generationTimeMs?: number;
}

/** Human-readable "how long it took" string, e.g. "820ms" or "4.3s". */
export function formatDuration(ms?: number): string {
  if (typeof ms !== "number" || !Number.isFinite(ms) || ms < 0) return "—";
  if (ms < 1000) return `${Math.round(ms)}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

const STORAGE_KEY = "career-e:model-runs";

type ModelRunMap = Partial<Record<LLMProvider, ModelRun>>;

function readStore(): ModelRunMap {
  if (typeof window === "undefined") return {};
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (!raw) return {};
    const parsed = JSON.parse(raw);
    return typeof parsed === "object" && parsed !== null ? (parsed as ModelRunMap) : {};
  } catch {
    return {};
  }
}

function writeStore(store: ModelRunMap): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(store));
  } catch {
    // Storage full/unavailable — comparison feature just won't persist this run.
  }
}

/** Save (or overwrite) the most recent run for a given provider. */
export function saveModelRun(run: ModelRun): void {
  const store = readStore();
  store[run.provider] = run;
  writeStore(store);
}

/** Get the most recent run for every provider that has one saved. */
export function getModelRuns(): ModelRunMap {
  return readStore();
}

/** Remove a single provider's saved run (e.g. "clear" in the comparison UI). */
export function clearModelRun(provider: LLMProvider): void {
  const store = readStore();
  delete store[provider];
  writeStore(store);
}

// ── Results history (every generated run, across all providers) ────────────
//
// Unlike `ModelRun` above (which only remembers the *latest* run per
// provider, for the dashboard's comparison panel), this store keeps a
// running log of every generated result set so the Results History page can
// show real past searches instead of static mock entries.

export interface ResultsHistoryEntry {
  id: string;
  timestamp: number;
  provider: LLMProvider;
  /** Wall-clock time (ms) the provider took to generate this result. */
  generationTimeMs?: number;
  confidencePercent: number;
  activeVariables: string;
  careers: CareerMatch[];
  /** Full snapshot of the assessment inputs that produced this result. */
  payload: FullAssessmentPayload;
}

const HISTORY_STORAGE_KEY = "career-e:results-history";
/** Cap how many entries we keep so localStorage doesn't grow unbounded. */
const MAX_HISTORY_ENTRIES = 30;

function readHistory(): ResultsHistoryEntry[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(HISTORY_STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as ResultsHistoryEntry[]) : [];
  } catch {
    return [];
  }
}

function writeHistory(entries: ResultsHistoryEntry[]): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(HISTORY_STORAGE_KEY, JSON.stringify(entries));
  } catch {
    // Storage full/unavailable — history just won't persist this entry.
  }
}

/** Save a newly generated result set to the history log. Returns the saved entry (with its new id). */
export function saveHistoryEntry(entry: Omit<ResultsHistoryEntry, "id">): ResultsHistoryEntry {
  const saved: ResultsHistoryEntry = {
    ...entry,
    id: `hist-${entry.timestamp}-${Math.random().toString(36).slice(2, 8)}`,
  };
  const entries = [saved, ...readHistory()].slice(0, MAX_HISTORY_ENTRIES);
  writeHistory(entries);
  return saved;
}

/** All saved history entries, most recent first. */
export function getHistoryEntries(): ResultsHistoryEntry[] {
  return readHistory().sort((a, b) => b.timestamp - a.timestamp);
}

/** Look up a single history entry by id (used to re-open a past result set). */
export function getHistoryEntry(id: string): ResultsHistoryEntry | undefined {
  return readHistory().find((e) => e.id === id);
}

/** Remove a single history entry. */
export function deleteHistoryEntry(id: string): void {
  writeHistory(readHistory().filter((e) => e.id !== id));
}

/** The top-scoring recommended career in a given entry, if any. */
export function topRecommendedCareer(entry: Pick<ResultsHistoryEntry, "careers">): CareerMatch | undefined {
  return [...entry.careers]
    .filter((c) => c.status === "recommended")
    .sort((a, b) => b.matchPercent - a.matchPercent)[0];
}
